In [51]:
import tensorflow as tf
import numpy as np

In [132]:
class ContextualBandit:

    def __init__(self):
        self.active_bandit = 0  # state
        self.bandits = np.array([
             [0.2, 0.0, 0.1, -4.0],  # 4th arm best
             [0.1, -5.0, 1.0, 0.25],  # 2nd arm best
             [-3.5, 2.0, 3.2, 6.4]  # 1st arm best
        ])
        self.num_bandits, self.num_actions = self.bandits.shape

    def get_bandit(self):
        self.active_bandit = np.random.randint(0, self.num_bandits)
        return self.active_bandit

    def pull(self, arm):
        bandit = self.bandits[self.active_bandit, arm]
        return 1 if np.random.randn(1) > bandit else -1

In [133]:
env = ContextualBandit()
num_actions = 4
contexts = 3
context = env.get_bandit()
context_one_hot = tf.expand_dims(tf.one_hot(context, contexts), 0)
W = tf.Variable(tf.random.normal([contexts, num_actions]))

In [134]:
def predict(context):
    print(context_one_hot)
    output = tf.sigmoid(tf.matmul(context_one_hot, W))
    best_action = tf.argmax(output, axis=1)
    return best_action

In [135]:
def random_or_predict(epsilon, context):
        if np.random.rand(1) < epsilon:
            return np.random.randint(num_actions)
        else:
            return predict(context)

In [136]:
action = random_or_predict(0.1, context)

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)


In [137]:
expected = np.argmax(output)
expected

1

In [138]:
reward = env.pull(action)
reward

1

In [139]:
a_ = tf.one_hot(action, 4)
a_

<tf.Tensor: id=712431, shape=(1, 4), dtype=float32, numpy=array([[0., 0., 0., 1.]], dtype=float32)>

In [140]:
from tensorflow.keras.layers import Dense

model = tf.keras.models.Sequential()
model.add(Dense(50, input_shape=(1,), activation='relu'))
model.add(Dense(25, activation='relu'))
model.add(Dense(4, activation='linear'))

model.compile(loss='mse', optimizer='adam')
model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_18 (Dense)             (None, 50)                100       
_________________________________________________________________
dense_19 (Dense)             (None, 25)                1275      
_________________________________________________________________
dense_20 (Dense)             (None, 4)                 104       
Total params: 1,479
Trainable params: 1,479
Non-trainable params: 0
_________________________________________________________________


In [141]:
model.fit([reward], a_, epochs=1)

Train on 1 samples
1/1 [==============================] - 0s 53ms/sample - loss: 0.2310


In [143]:
for _ in range(2000):
    action = random_or_predict(0.1, context)
    output = tf.sigmoid(tf.matmul(context_one_hot, W))
    expected = np.argmax(output)
    reward = env.pull(action)
    a_ = tf.one_hot(action, 4)
    model.fit([reward], a_, epochs=1)

Train on 1 samples
1/1 [==============================] - 0s 72ms/sample - loss: 0.8754
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.2138
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 0.0711
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.2008
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.1944
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0649
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.1825
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.1771
tf.Tensor([[1. 0. 0.]], shape=(1, 3), 

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0033
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0028
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0023
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0019
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0015
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0012
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 9.0293e-04
tf.Tensor([[1. 0

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 8.4908e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 8.2671e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 7.8595e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 7.3126e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 6.6725e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 5.9828e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 5.2

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0030
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0031
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 0.0031
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0032
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0032
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0031
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0031
tf.Tensor([[1. 0. 0.

1/1 [==============================] - 0s 2ms/sample - loss: 1.2333e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 1.1933e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 1.1569e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 1.1210e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 1.0833e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 1.0423e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 9.9672e-06
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0027
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0031
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0034
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0037
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0039
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0040
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0041
tf.Tensor([[1. 0. 0.

Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 2.9755e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 2.7881e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 2.5639e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 2.3142e-05
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.2529
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 9.8070e-06
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 4.9188e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [=========================

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 8.7951e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 7.4132e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 6.3250e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 5.4791e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 4.8274e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 4.3269e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 3.9

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0036
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 0.0038
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 0.0039
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0039
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0039
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0038
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.6795
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 2.2501e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 1.8662e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 1.5452e-04
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.2417
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 1.7296e-04
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.2362
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 4.3580e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [=============================

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 6.6099e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 5.6463e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 4.7457e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 3.9224e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 3.1861e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 2.5418e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 1.9

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 0.0048
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0049
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0048
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0047
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0045
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0042
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0039
Train on 1 samples
1

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 8.4601e-04
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.5017
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0011
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0013
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0014
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0015
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0016
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 sampl

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 8.3524e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 6.2641e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 4.6179e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 3.3634e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 2.4474e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 1.8159e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 1.4

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0015
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0017
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0018
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0019
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0020
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.2612
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0018
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 1.8102e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 2.4561e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 5ms/sample - loss: 3.1035e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 3.7050e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 4.2262e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 4.6441e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 4.9

1/1 [==============================] - 0s 3ms/sample - loss: 0.0018
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0017
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0017
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0016
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0015
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0014
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 0.0013
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [===============

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 1.2931e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 1.1268e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 5ms/sample - loss: 9.7196e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 8.3112e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 7.0565e-05
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.4930
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 3.5993e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float

1/1 [==============================] - 0s 4ms/sample - loss: 0.0015
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 0.0018
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0021
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 0.0023
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 0.0025
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 0.0025
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0026
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [===============

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0053
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0054
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0054
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0054
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0052
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0049
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0046
tf.Tensor([[1. 0. 0.

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 7.8891e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 7.4574e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 6.9408e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 6.3642e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 5.7509e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 5.1224e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 4.4

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0011
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0011
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0011
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0011
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0011
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0010
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 9.8863e-04
tf.Tensor([[1. 0

Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 1.7011e-06
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 1.4724e-06
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.2504
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 2.7977e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 9.8946e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 1.9734e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 3.0910e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [=========================

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 3.9583e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 4.1311e-05
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.1981
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.2556
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.2507
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 8.3832e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 3.1379e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 6.3487e-04
tf.Tensor([[1. 0. 0

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 2.5876e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 2.4120e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 2.3369e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 2.3363e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 2.3867e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 2.4672e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 2.5

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 5.2225e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 4.7723e-04
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.3571
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.3479
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 3.1992e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 2.7863e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 2.4826e-04
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.2117
tf.Tensor([[1. 0. 0

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 6.2267e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 5.4497e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 4.7005e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 3.9956e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 3.3470e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 2.7632e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 2.2

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0018
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.2127
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0016
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0016
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0016
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0015
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0015
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1

1/1 [==============================] - 0s 3ms/sample - loss: 0.0014
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0012
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0010
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 8.6310e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 7.1435e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 5.8314e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 4.6940e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 3.0050e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 6ms/sample - loss: 4.0328e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 5ms/sample - loss: 4.9952e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 5.8385e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 6.5270e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 7.0407e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 7.3

Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.7399
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0015
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0015
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0016
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0017
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0018
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0019
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 4.7813e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 3.8669e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 3.0724e-04
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.2349
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 3.2200e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 4.0058e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 4.7116e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float

1/1 [==============================] - 0s 3ms/sample - loss: 7.3666e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 7.9494e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 8.3266e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 8.5016e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 8.4876e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 8.3045e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 7.9767e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0016
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0016
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0015
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.2148
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0015
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.2104
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0022
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample -

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 1.3521e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 1.5754e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 1.9108e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 2.3062e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 2.7187e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 3.1142e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 3.4

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0046
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 0.0044
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.1994
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0042
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0042
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0042
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0041
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 3.0775e-04
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.2319
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 6.1852e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 8.8374e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0011
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0014
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0016
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 1.7559e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 1.2957e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 9.3667e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 6.6426e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 4.6489e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 3.2592e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 2.3

1/1 [==============================] - 0s 3ms/sample - loss: 8.1766e-04
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.7600
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.2253
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 8.1162e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0010
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0012
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0014
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0016
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float3

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 8.1138e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 8.0129e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 7.7695e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 6ms/sample - loss: 7.4068e-04
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.5030
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0884
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 5.5497e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [=============================

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0016
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0017
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0016
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 0.0016
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0016
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0015
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 0.0014
tf.Tensor([[1. 0. 0.

Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.2085
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0020
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0020
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.5020
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0020
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0019
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0019
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.1004
tf.Tensor([[1. 0. 0.]], shape=(1, 3), d

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0022
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.2065
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0891
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0030
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0033
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0036
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0037
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample -

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 0.0014
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0012
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0011
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 9.4400e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 8.2123e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 7.0720e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 6.0246e-04
tf.T

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 2.2269e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 1.7496e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 1.3499e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 1.0213e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 7.5690e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 5.4913e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 3.9

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 6.1939e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 4.9170e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 3.8726e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 3.0356e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 2.3798e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 1.8791e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 1.5

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 5.8461e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 4.7921e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 3.8649e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 3.0626e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 2.3803e-04
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0415
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 1.3913e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float

Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 1.7590e-06
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 1.3887e-06
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0227
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 1.4023e-06
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 1.7236e-06
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 2.0189e-06
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 2.2723e-06
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [=========================

1/1 [==============================] - 0s 3ms/sample - loss: 0.0017
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0016
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0016
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0015
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0014
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0013
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.7005
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0015
tf.Te

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 1.3403e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 1.6172e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 1.8661e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 2.0788e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 2.2506e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 2.3793e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 2.4

1/1 [==============================] - 0s 3ms/sample - loss: 0.0037
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0039
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 5ms/sample - loss: 0.0040
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0041
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0041
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0040
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0040
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 0.2079
tf.Te

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 4.1991e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 3.7134e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 3.2515e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 2.8171e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 2.4133e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 2.0424e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 1.7

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0011
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0012
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0012
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0013
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0013
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0743
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0014
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0039
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0037
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0035
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0033
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0032
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0031
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 0.0030
tf.Tensor([[1. 0. 0.

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0026
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0024
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0022
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0020
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0018
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0016
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0014
tf.Tensor([[1. 0. 0.

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 1.8294e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 1.0071e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 4.8224e-06
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 1.9588e-06
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 9.5337e-07
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 1.3828e-06
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 2.8

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0028
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0031
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0033
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0034
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0035
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 0.0035
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0034
tf.Tensor([[1. 0. 0.

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0036
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 0.0037
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0038
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0039
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0038
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0037
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0036
tf.Tensor([[1. 0. 0.

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 0.0105
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0103
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0101
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0097
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0093
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0089
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0084
tf.Tensor([[1. 0. 0.

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 9.1720e-06
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 1.1867e-05
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.2524
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 1.5669e-05
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0704
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 9.6914e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 1.6333e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [=============================

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 1.0782e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 8.7756e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 7.0191e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 5.5068e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 4.2274e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 3.1658e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 2.3

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 5ms/sample - loss: 5.2208e-05
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 0.2417
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 2.4888e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 4.7396e-04
Train on 1 samples
1/1 [==============================] - 0s 5ms/sample - loss: 0.2237
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 0.0013
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 0.0018
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 1.3246e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 1.5948e-04
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 0.2381
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 3.1811e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 4.7284e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 6.3396e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 7.9040e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 9.0177e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 8.3874e-04
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.2556
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 6.5428e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 5.8116e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 5.4303e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 5.3085e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 4.3664e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 4.1603e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 3.9185e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 3.6497e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 3.3624e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 3.0645e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 2.7

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0013
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0012
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0012
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0011
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0011
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0010
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 9.5457e-04
tf.Tensor([[1. 0

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 4.6746e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 4.0511e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 3.4863e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 2.9778e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 2.5228e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 2.1187e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 1.7

Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.2339
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 4.5608e-04
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.2301
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 5.7913e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 7.1952e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 8.4587e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 9.5346e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [=============================

Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.2552
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 2.3562e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 3.4994e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 4.8123e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 6.1842e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 7.5310e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 8.7909e-04
Train on 1 samples
1/1 [=========================

Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0040
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0039
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0038
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0037
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0036
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0034
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0032
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1

1/1 [==============================] - 0s 3ms/sample - loss: 0.0015
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.3241
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0013
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0012
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0011
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 9.7366e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 8.6489e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 7.62

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 5ms/sample - loss: 0.0074
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 0.0071
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 0.0067
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0063
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.1852
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 0.1818
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 5ms/sample - loss: 0.0057
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample -

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 3.1285e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 2.4759e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 1.9239e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 1.4646e-04
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.2402
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 1.5530e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 2.0343e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 9.3947e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 1.3907e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 1.8974e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 2.4150e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 2.9087e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 3.3532e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 3.7

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0022
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0022
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0022
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0021
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0020
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0019
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0017
tf.Tensor([[1. 0. 0.

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0039
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0039
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0038
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0036
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.1988
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0036
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0037
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 5.9997e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 6.8212e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 8.5633e-05
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 1.0877e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 1.3475e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 1.6129e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 1.8

Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.0019
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0017
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0015
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0014
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0012
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 0.0011
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 9.1555e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 sampl

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 3.9669e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 3.4410e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 2.9595e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 2.5223e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 2.1290e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 1.7784e-04
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 0.2381
Train on 1 samples
1/1 [=========================

1/1 [==============================] - 0s 3ms/sample - loss: 8.6048e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 7.4560e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 6.4296e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 5.5181e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 4.7118e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 4.0008e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 3.3752e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 

tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 6.8576e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 6.3215e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 5.7582e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 5.1847e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 3ms/sample - loss: 4.6160e-04
tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Train on 1 samples
1/1 [==============================] - 0s 2ms/sample - loss: 4.0643e-04
Train on 1 samples
1/1 [==============================] - 0s 4ms/sample - loss: 0.2320
Train on 1 samples
1/1 [=========================

In [144]:
W

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.03822796,  0.927771  ,  0.19020668,  0.99942946],
       [ 0.57355326,  0.0158124 ,  0.66909814, -1.5567929 ],
       [ 1.0886842 , -0.38175115, -0.29722777, -0.16104403]],
      dtype=float32)>

In [145]:
             [0.2, 0.0, 0.1, -4.0],  # 4th arm best
             [0.1, -5.0, 1.0, 0.25],  # 2nd arm best
             [-3.5, 2.0, 3.2, 6.4]  # 1st arm best

[0.1, -5.0, 1.0, 0.25]

In [146]:
model.losses

[]